---
- name: Install Tomcat to remote server
  hosts: all
  become: yes
  tasks:
   - name: Create group
     group:
      name: tomcat
      state: present

   - name: Create user
     user:
        name: tomcat
        state: present

   - name: Update apt packages
     apt:
      upgrade: yes
      update_cache: yes

   - name: Download Open JDK
     apt:
      name: default-jdk
      state: present

   - name: Check Java version
     shell: java -version
     register: version
     notify: version

   - name: Create a Directory /opt/tomcat
     file:
      path: /opt/tomcat
      state: directory
      mode: 0755
      owner: tomcat
      group: tomcat

   - name: Download Tomcat
     unarchive:
      src: https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.27/bin/apache-tomcat-10.0.27.tar.gz
      dest: /opt/tomcat
      remote_src: yes

   - name: Change ownership
     file:
      path: /opt/tomcat
      owner: tomcat
      group: tomcat
      mode: "u+rwx,g+rx,o=rx"
      recurse: yes
      state: directory

  #  - name: Tomcat users edit
  #    copy:
  #     content: |-
  #       <?xml version="1.0" encoding="UTF-8"?>
  #       <tomcat-users xmlns="http://tomcat.apache.org/xml"
  #                     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  #                     xsi:schemaLocation="http://tomcat.apache.org/xml tomcat-users.xsd"
  #                     version="1.0">
  #       <role rolename="manager-gui" />
  #       <user username="manager" password="manager123" roles="manager-gui" />

  #       <role rolename="admin-gui" />
  #       <user username="admin" password="admin123" roles="manager-gui,admin-gui" />
  #       </tomcat-users>
  #     dest: /opt/tomcat/conf/tomcat-users.xml
      
  #  - name: Tomcat manager edit
  #    copy:
  #     content: |-
  #       <?xml version="1.0" encoding="UTF-8"?>
  #       <Context antiResourceLocking="false" privileged="true" >
  #         <CookieProcessor className="org.apache.tomcat.util.http.Rfc6265CookieProcessor"
  #                         sameSiteCookies="strict" />
  #         <!-- <Valve className="org.apache.catalina.valves.RemoteAddrValve"
  #               allow="127\.\d+\.\d+\.\d+|::1|0:0:0:0:0:0:0:1" /> -->
  #         <Manager sessionAttributeValueClassNameFilter="java\.lang\.(?:Boolean|Integer|Long|Number|String)|org\.apache\.catalina\.filters\.CsrfPreventionFilter\$LruCache(?:\$1)?|java\.util\.(?:Linked)?HashMap"/>
  #       </Context>
  #     dest: /opt/tomcat/webapps/manager/META-INF/context.xml

  #  - name: Tomcat host-manager edit
  #    copy:
  #     content: |-
  #       <?xml version="1.0" encoding="UTF-8"?>
  #       <Context antiResourceLocking="false" privileged="true" >
  #         <CookieProcessor className="org.apache.tomcat.util.http.Rfc6265CookieProcessor"
  #                         sameSiteCookies="strict" />
  #         <!-- <Valve className="org.apache.catalina.valves.RemoteAddrValve"
  #               allow="127\.\d+\.\d+\.\d+|::1|0:0:0:0:0:0:0:1" /> -->
  #         <Manager sessionAttributeValueClassNameFilter="java\.lang\.(?:Boolean|Integer|Long|Number|String)|org\.apache\.catalina\.filters\.CsrfPreventionFilter\$LruCache(?:\$1)?|java\.util\.(?:Linked)?HashMap"/>
  #       </Context>
  #     dest: /opt/tomcat/webapps/host-manager/META-INF/context.xml

   - name: Creating a service file
     copy:
      content: |-
        [Unit]
        Description=Tomcat Service
        Requires=network.target
        After=network.target

        [Service]
        Type=forking
        User=tomcat
        Group=tomcat

        Environment="JAVA_HOME=/usr/lib/jvm/java-1.11.0-openjdk-amd64"
        Environment="JAVA_OPTS=-Djava.security.egd=file:///dev/urandom"
        Environment="CATALINA_PID=/opt/tomcat/logs/tomcat.pid"
        Environment="CATALINA_BASE=/opt/tomcat"
        Environment="CATALINA_HOME=/opt/tomcat"
        Environment="CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC"

        ExecStart=/opt/tomcat/bin/startup.sh
        ExecStop=/opt/tomcat/bin/shutdown.sh
        Restart=always
        RestartSec=10

        [Install]
        WantedBy=multi-user.target
      dest: /etc/systemd/system/tomcat.service

   - name: Reload the SystemD
     systemd:
        daemon-reload: yes

   - name: Start and enable tomcat
     systemd:
        name: tomcat
        enabled: yes
        state: started

   - name: Connect to Tomcat server on port 8080
     tags: test
     uri:
       url: http://localhost:8080
     register: result
     until: "result.status == 200"
     retries: 5
     delay: 10

  handlers:
    - name: version
      debug:
        var: version.stderr

